<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_acceuil' => [[], ['_controller' => 'App\\Controller\\AcceuilController::index'], [], [['text', '/Acceuil']], [], [], []],
    'app_visiteur' => [[], ['_controller' => 'App\\Controller\\VisiteurController::index'], [], [['text', '/Visiteur']], [], [], []],
    'app_visiteur_connecter' => [[], ['_controller' => 'App\\Controller\\VisiteurController::Authentification'], [], [['text', '/Visiteur/Connecter']], [], [], []],
    'app_consulter' => [[], ['_controller' => 'App\\Controller\\VisiteurController::Consulter'], [], [['text', '/Visiteur/Consulter']], [], [], []],
    'app_renseigner' => [[], ['_controller' => 'App\\Controller\\VisiteurController::Renseigner'], [], [['text', '/Visiteur/Renseigner']], [], [], []],
    'app_espace_visiteur' => [[], ['_controller' => 'App\\Controller\\VisiteurController::Espace'], [], [['text', '/Visiteur/Espace']], [], [], []],
    'app_visiteur_deconnexion' => [[], ['_controller' => 'App\\Controller\\VisiteurController::Deconnecter'], [], [['text', '/visiteur/deconnecter']], [], [], []],
    'app_comptable' => [[], ['_controller' => 'App\\Controller\\ComptableController::index'], [], [['text', '/Comptable']], [], [], []],
    'app_comptable_connecter' => [[], ['_controller' => 'App\\Controller\\ComptableController::Authentification'], [], [['text', '/Comptable/Connecter']], [], [], []],
    'app_valider' => [[], ['_controller' => 'App\\Controller\\ComptableController::Valider'], [], [['text', '/Comptable/Valider']], [], [], []],
    'app_suivre' => [[], ['_controller' => 'App\\Controller\\ComptableController::Suivre'], [], [['text', '/Comptable/Suivre']], [], [], []],
    'app_espace_comptable' => [[], ['_controller' => 'App\\Controller\\ComptableController::Espace'], [], [['text', '/Comptable/Espace']], [], [], []],
    'app_comptable_deconnexion' => [[], ['_controller' => 'App\\Controller\\ComptableController::Deconnecter'], [], [['text', '/Comptable/deconnecter']], [], [], []],
];
